<?php

namespace Database\Seeders;

use App\Models\Driver;
use App\Models\FuelRecord;
use App\Models\Project;
use App\Models\Vehicle;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class FuelRecordsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $records = [
            // Registros del reporte mensual
            [
                'folio' => 1,
                'vehicle' => 'TRANSIT',
                'date' => '2025-12-01',
                'return_date' => null,
                'driver' => 'MARTIN MARTINEZ',
                'provider' => 'HOME DEPOT',
                'description' => 'COMPRAS',
                'destination' => 'TLALNEPANTLA',
                'initial_mileage' => 256742,
                'final_mileage' => 256756,
                'liters' => 2.00,
                'cost_per_liter' => 26.20,
                'total_cost' => 52.40,
                'fuel_type' => 'gasoline',
            ],
            [
                'folio' => 2,
                'vehicle' => 'AVEO-2',
                'date' => '2025-12-01',
                'return_date' => null,
                'driver' => 'MANUEL CARDONA',
                'provider' => 'GASOLINERIA',
                'description' => 'LLENADO DE BIDONES',
                'destination' => 'TLALNEPANTLA',
                'initial_mileage' => 157618,
                'final_mileage' => 157629,
                'liters' => 0.85,
                'cost_per_liter' => 23.39,
                'total_cost' => 19.79,
                'fuel_type' => 'gasoline',
            ],
            [
                'folio' => 3,
                'vehicle' => 'AVEO-1',
                'date' => '2025-12-01',
                'return_date' => null,
                'driver' => 'HECTOR AVILES',
                'provider' => 'SAM\'S',
                'description' => 'COMPRAS',
                'destination' => 'TLALNEPANTLA',
                'initial_mileage' => 172763,
                'final_mileage' => 172781,
                'liters' => 1.64,
                'cost_per_liter' => 23.39,
                'total_cost' => 38.27,
                'fuel_type' => 'gasoline',
            ],
            [
                'folio' => 4,
                'vehicle' => 'AVEO-1',
                'date' => '2025-12-01',
                'return_date' => null,
                'driver' => 'HECTOR AVILES',
                'provider' => 'SAM\'S',
                'description' => 'COMPRAS',
                'destination' => 'TLALNEPANTLA',
                'initial_mileage' => 172781,
                'final_mileage' => 172785,
                'liters' => 0.36,
                'cost_per_liter' => 23.39,
                'total_cost' => 8.51,
                'fuel_type' => 'gasoline',
            ],
            [
                'folio' => 5,
                'vehicle' => 'F-350',
                'date' => '2025-12-02',
                'return_date' => null,
                'driver' => 'HECTOR AVILES',
                'provider' => 'VERIFICENTRO',
                'description' => 'VERIFICAR UNIDAD',
                'destination' => 'TULTITLAN',
                'initial_mileage' => 433035,
                'final_mileage' => 433061,
                'liters' => 6.50,
                'cost_per_liter' => 23.39,
                'total_cost' => 152.04,
                'fuel_type' => 'diesel',
            ],
            [
                'folio' => 6,
                'vehicle' => 'AVEO-2',
                'date' => '2025-12-02',
                'return_date' => null,
                'driver' => 'HECTOR AVILES',
                'provider' => 'LIVERPOOL',
                'description' => 'FACTURACION',
                'destination' => 'TLALNEPANTLA',
                'initial_mileage' => 157629,
                'final_mileage' => 157642,
                'liters' => 1.00,
                'cost_per_liter' => 23.39,
                'total_cost' => 23.39,
                'fuel_type' => 'gasoline',
            ],
            [
                'folio' => 7,
                'vehicle' => 'F-350',
                'date' => '2025-12-02',
                'return_date' => null,
                'driver' => 'ALEJANDRO RODRIGUEZ',
                'provider' => 'EGSA',
                'description' => '',
                'destination' => 'TLALNEPANTLA',
                'initial_mileage' => 433061,
                'final_mileage' => 433094,
                'liters' => 8.25,
                'cost_per_liter' => 23.39,
                'total_cost' => 192.97,
                'fuel_type' => 'diesel',
            ],
            [
                'folio' => 8,
                'vehicle' => 'AVEO-2',
                'date' => '2025-12-02',
                'return_date' => null,
                'driver' => 'HECTOR AVILES',
                'provider' => 'SAM\'S BANCOS',
                'description' => 'COMPRAS',
                'destination' => 'TLALNEPANTLA',
                'initial_mileage' => 157642,
                'final_mileage' => 157648,
                'liters' => 0.46,
                'cost_per_liter' => 23.39,
                'total_cost' => 10.80,
                'fuel_type' => 'gasoline',
            ],
            [
                'folio' => 9,
                'vehicle' => 'AVEO-1',
                'date' => '2025-12-03',
                'return_date' => null,
                'driver' => 'JUAN CARLOS LOPEZ',
                'provider' => 'HOME DEPOT',
                'description' => 'COMPRAS',
                'destination' => 'TLALNEPANTLA',
                'initial_mileage' => 172785,
                'final_mileage' => 172805,
                'liters' => 1.82,
                'cost_per_liter' => 23.39,
                'total_cost' => 42.53,
                'fuel_type' => 'gasoline',
            ],
            [
                'folio' => 10,
                'vehicle' => 'AVEO-2',
                'date' => '2025-12-03',
                'return_date' => null,
                'driver' => 'HECTOR AVILES',
                'provider' => 'ARRENDADORA TURBO',
                'description' => 'RECOLECCION DE DOCTOS',
                'destination' => 'HUXQUILUCAN',
                'initial_mileage' => 157648,
                'final_mileage' => 157692,
                'liters' => 3.38,
                'cost_per_liter' => 23.39,
                'total_cost' => 79.17,
                'fuel_type' => 'gasoline',
            ],
            [
                'folio' => 11,
                'vehicle' => 'AVEO-1',
                'date' => '2025-12-03',
                'return_date' => null,
                'driver' => 'JUAN CARLOS LOPEZ',
                'provider' => 'MECANICO',
                'description' => 'TRASLADO DE PERSONAL',
                'destination' => 'TLALNEPANTLA',
                'initial_mileage' => 172805,
                'final_mileage' => 172806,
                'liters' => 0.09,
                'cost_per_liter' => 23.39,
                'total_cost' => 2.13,
                'fuel_type' => 'gasoline',
            ],
            [
                'folio' => 12,
                'vehicle' => 'HINO',
                'date' => '2025-12-03',
                'return_date' => null,
                'driver' => 'MARTIN MARTINEZ',
                'provider' => 'MECANICO',
                'description' => 'MANTENIMIENTO',
                'destination' => 'TLALNEPANTLA',
                'initial_mileage' => 97461,
                'final_mileage' => 97463,
                'liters' => 0.50,
                'cost_per_liter' => 26.20,
                'total_cost' => 13.10,
                'fuel_type' => 'diesel',
            ],
            [
                'folio' => 13,
                'vehicle' => 'AVEO-1',
                'date' => '2025-12-03',
                'return_date' => '2025-12-04',
                'driver' => 'MARTIN MARTINEZ',
                'provider' => '',
                'description' => '',
                'destination' => 'CHALCO',
                'initial_mileage' => 172806,
                'final_mileage' => 172966,
                'liters' => 14.55,
                'cost_per_liter' => 23.39,
                'total_cost' => 340.22,
                'fuel_type' => 'gasoline',
            ],
            [
                'folio' => 14,
                'vehicle' => 'AVEO-2',
                'date' => '2025-12-03',
                'return_date' => null,
                'driver' => 'JUAN CARLOS LOPEZ',
                'provider' => 'MECANICO',
                'description' => 'TRASLADO DE PERSONAL',
                'destination' => 'TLALNEPANTLA',
                'initial_mileage' => 157692,
                'final_mileage' => 157696,
                'liters' => 0.31,
                'cost_per_liter' => 23.39,
                'total_cost' => 7.20,
                'fuel_type' => 'gasoline',
            ],
            [
                'folio' => 15,
                'vehicle' => 'AVEO-2',
                'date' => '2025-12-03',
                'return_date' => null,
                'driver' => 'HECTOR AVILES',
                'provider' => 'SAM\'S WALMART',
                'description' => 'COMPRAS',
                'destination' => 'TLALNEPANTLA',
                'initial_mileage' => 157696,
                'final_mileage' => 157716,
                'liters' => 1.54,
                'cost_per_liter' => 23.39,
                'total_cost' => 35.98,
                'fuel_type' => 'gasoline',
            ],
            [
                'folio' => 16,
                'vehicle' => 'AVEO-1',
                'date' => '2025-12-04',
                'return_date' => null,
                'driver' => 'JUAN CARLOS LOPEZ',
                'provider' => 'MECANICO',
                'description' => 'TRASLADO DE PERSONAL',
                'destination' => 'TLALNEPANTLA',
                'initial_mileage' => 172966,
                'final_mileage' => 172970,
                'liters' => 0.36,
                'cost_per_liter' => 23.39,
                'total_cost' => 8.51,
                'fuel_type' => 'gasoline',
            ],
            [
                'folio' => 17,
                'vehicle' => 'HINO',
                'date' => '2025-12-04',
                'return_date' => null,
                'driver' => 'MANUEL CARDONA',
                'provider' => 'MECANICO',
                'description' => 'MANTENIMIENTO',
                'destination' => 'TLALNEPANTLA',
                'initial_mileage' => 97463,
                'final_mileage' => 97465,
                'liters' => 0.50,
                'cost_per_liter' => 26.20,
                'total_cost' => 13.10,
                'fuel_type' => 'diesel',
            ],
            [
                'folio' => 18,
                'vehicle' => 'TRANSIT',
                'date' => '2025-12-04',
                'return_date' => '2025-12-05',
                'driver' => 'MARTIN MARTINEZ',
                'provider' => '',
                'description' => 'RECOLECCION PERSONAL',
                'destination' => 'TLALNEPANTLA',
                'initial_mileage' => 256756,
                'final_mileage' => 256832,
                'liters' => 10.86,
                'cost_per_liter' => 26.20,
                'total_cost' => 284.46,
                'fuel_type' => 'diesel',
            ],
            [
                'folio' => 19,
                'vehicle' => 'AVEO-2',
                'date' => '2025-12-04',
                'return_date' => null,
                'driver' => 'HECTOR AVILES',
                'provider' => 'AEROMEXICO CARGO',
                'description' => 'DOCUMENTAR',
                'destination' => 'VENUSTIANO CARRANZA',
                'initial_mileage' => 157727,
                'final_mileage' => 158814,
                'liters' => 6.69,
                'cost_per_liter' => 23.39,
                'total_cost' => 156.53,
                'fuel_type' => 'gasoline',
            ],
            [
                'folio' => 20,
                'vehicle' => 'AVEO-1',
                'date' => '2025-12-04',
                'return_date' => null,
                'driver' => 'MANUEL CARDONA',
                'provider' => '',
                'description' => '',
                'destination' => 'CHALCO',
                'initial_mileage' => 172970,
                'final_mileage' => 173168,
                'liters' => 18.00,
                'cost_per_liter' => 23.39,
                'total_cost' => 421.02,
                'fuel_type' => 'gasoline',
            ],
            [
                'folio' => 21,
                'vehicle' => 'HINO',
                'date' => '2025-12-05',
                'return_date' => '2025-12-06',
                'driver' => 'JUAN CARLOS LOPEZ',
                'provider' => 'MECANICO',
                'description' => 'MANTENIMIENTO',
                'destination' => 'TLALNEPANTLA',
                'initial_mileage' => 97465,
                'final_mileage' => 97468,
                'liters' => 0.75,
                'cost_per_liter' => 26.20,
                'total_cost' => 19.65,
                'fuel_type' => 'diesel',
            ],
        ];

        foreach ($records as $record) {
            $vehicle = Vehicle::where('unit', $record['vehicle'])->first();
            $driver = Driver::where('name', $record['driver'])->first();
            $project = null;
            
            if (!empty($record['provider'])) {
                $project = Project::where('name', 'like', '%' . $record['provider'] . '%')->first();
            }

            if ($vehicle && $driver) {
                FuelRecord::create([
                    'folio' => 'F-' . str_pad($record['folio'], 4, '0', STR_PAD_LEFT),
                    'vehicle_id' => $vehicle->id,
                    'driver_id' => $driver->id,
                    'project_id' => $project?->id,
                    'date' => Carbon::createFromFormat('Y-m-d', $record['date'])->toDateTimeString(),
                    'return_date' => $record['return_date'] ? Carbon::createFromFormat('Y-m-d', $record['return_date'])->toDateTimeString() : null,
                    'shift' => 'day',
                    'provider_client' => $record['provider'] ?? null,
                    'destination' => $record['destination'],
                    'initial_mileage' => $record['initial_mileage'],
                    'final_mileage' => $record['final_mileage'],
                    'liters' => $record['liters'],
                    'fuel_price' => $record['cost_per_liter'],
                    'cost' => $record['total_cost'],
                    'km_per_liter' => round(($record['final_mileage'] - $record['initial_mileage']) / $record['liters'], 2),
                    'description' => $record['description'],
                    'evidence' => json_encode([]),
                ]);
            }
        }
    }
}
